name: Loveleen - Dev Workflow
on: workflow_dispatch         #manualy triger the workflow
jobs: 
  first-job:
    runs-on: ubutu-latest
    steps:  
      - name: Print Greetings
        run: echo " HEllo World" 
      - name: Print Good Bye
        run: echo " Bye BYe Github"
      
